name: CI/CD - EventHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next

  terraform:
    name: Terraform Infrastructure
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve

  deploy:
    name: Deploy to AWS Amplify
    needs: [ build, terraform ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: .next

      - name: Deploy to Amplify
        uses: aws-actions/aws-amplify-deploy@v1
        with:
          app-id: ${{ secrets.AMPLIFY_APP_ID }}
          branch-name: main
          artifact: .next
          region: us-east-2
