name: Deploy EventHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next

  terraform:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/terraform
        env:
          TF_VAR_github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./infra/terraform
        env:
          TF_VAR_github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: terraform apply -auto-approve

  deploy:
    needs: [build, terraform]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: .next

      - name: Deploy to AWS Amplify
        uses: aws-actions/aws-amplify-deploy@v1
        with:
          app-id: ${{ secrets.AMPLIFY_APP_ID }}
          branch-name: main
          artifact: .next
          region: us-east-2
